apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: scala-spark-minio-streaming-test
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: bitnami/spark:3.5.5-debian-12-r1
  imagePullPolicy: IfNotPresent
  sparkVersion: 3.5.5
  mainClass: fr.umontpellier.polytech.MinioStreamingTest
  mainApplicationFile: http://minio.minio.svc.cluster.local:9000/mybucket/scala-spark.jar
  driver:
    labels:
      version: 3.5.5
    cores: 1
    memory: 1024m
    serviceAccount: spark-operator-spark
  executor:
    labels:
      version: 3.5.5
    instances: 3
    cores: 1
    memory: 1024m
