apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: scala-spark-stackoverflow
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.3
  imagePullPolicy: IfNotPresent
  sparkVersion: 3.5.3
  mainClass: fr.umontpellier.polytech.StackOverflowTest
  mainApplicationFile: http://minio.minio.svc.cluster.local:9000/mybucket/scala-spark.jar
  deps:
    files:
      - http://minio.minio.svc.cluster.local:9000/mybucket/data/stackoverflow.csv
  driver:
    labels:
      version: 3.5.3
    cores: 1
    memory: 1024m
    serviceAccount: spark-operator-spark
  executor:
    labels:
      version: 3.5.3
    instances: 1
    cores: 1
    memory: 1024m
