services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: none
      # Java config
      NEO4J_dbms.jvm.additional: "-Dlog4j2.formatMsgNoLookups=true"
      NEO4J_dbms.memory.heap.initial_size: 1024m
      NEO4J_dbms.memory.heap.max_size: 4G
      NEO4J_dbms.memory.pagecache.size: 512m
      # Plugins
      NEO4J_PLUGINS: '["apoc"]'
      # APOC config
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
    volumes:
      - ".neo4j_data/:/data"
      - "./data/:/var/lib/neo4j/import/data/"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
